### ISSUE TITLE
You don't know what MVC is.

### ISSUE THREAD

**Issue by LeoNatan** [theswiftdev/viperb#1]
> **MVC**
> 
> The Model-View-Controller (Massive-View-Controller) pattern is a basic concept. You have usually a huge UIViewController subclass that controls all the views and collects every model that needed to be displayed for the end user. For example you call an API endpoint using URLSession or Alamofire from the controller, do the response data validation and formatting then you implement your table or collection view delegates on the view controller, so basically all the application logic goes inside that single overstuffed miserable view controller class. Does this ring a bell for you? 🙄

No, that's not what MVC is. Please go back to high school and learn what is MVC.

🙄

**Comment by tib** [comment]
lol :D you are funny.
